### ISSUE TITLE
Felix Plugin

### ISSUE THREAD

**Issue by cmoulliard** [szhem/camel-osgi#8]
Hi,

You should use the following version of maven-felix-plugin 2.3.6, otherwise it fails to build and generate the follwing error :

Caused by: java.lang.ClassNotFoundException: aQute.lib.osgi.Resource
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
    ... 54 more

Regards,

Charles

**Comment by szhem** [comment]
Hi Charles,

Thanks for reporting the issue. Fix has been commited. Could you confirm that it has been fixed, as I didn't expect the exception with maven-felix-plugin 2.3.5 version too.

Regards,
Sergey
